# Generated by Django 6.1.1 on 2026-10-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=80)),
                ('name_ar', models.CharField(blank=True, max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='menu/categories/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.brand')),
                ('outlet', models.ForeignKey(blank=True, help_text='Null = brand-level category (mandatory base)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.outlet')),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(blank=True, max_length=120)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='menu/items/')),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('dietary_type', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-vegetarian'), ('vegan', 'Vegan')], default='non_veg', max_length=8)),
                ('spice_level', models.CharField(choices=[('none', 'Not spicy'), ('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot')], default='none', max_length=8)),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('available', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menucategory')),
                ('outlet', models.ForeignKey(blank=True, help_text='Null = brand-level item (mandatory base)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.outlet')),
                ('overrides', models.ForeignKey(blank=True, help_text='Outlet item that overrides this brand-level item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlet_versions', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
