# Generated by Django 6.0.8 on 2026-10-06 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_brand_default_menu_url_brand_default_ordering_url_and_more'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='spice_level',
            field=models.CharField(choices=[('none', 'Not spicy'), ('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot'), ('extra_hot', 'Extra hot')], default='none', max_length=12),
        ),
        migrations.CreateModel(
            name='MenuSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('menu_type', models.CharField(choices=[('pages', 'Booklet (Page Images)'), ('pdf', 'PDF Document'), ('external_url', 'External Website Link')], default='pages', max_length=16)),
                ('menu_file', models.FileField(blank=True, upload_to='menu/pdf/')),
                ('menu_url', models.URLField(blank=True, help_text='Used when menu_type is external_url')),
                ('ordering_url', models.URLField(blank=True, help_text="Optional outbound 'Order Online' link")),
                ('active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_sources', to='core.brand')),
                ('outlet', models.ForeignKey(blank=True, help_text='Null = brand-level menu source', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_sources', to='core.outlet')),
            ],
            options={
                'verbose_name': 'Menu Source',
                'verbose_name_plural': 'Menu Sources',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SpecialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('signature', 'Signature Dish'), ('weekend', 'Weekend Special'), ('offer', 'Special Offer')], default='signature', max_length=16)),
                ('title_en', models.CharField(max_length=140)),
                ('title_ar', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='menu/specials/')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('discount_label', models.CharField(blank=True, max_length=60)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specials', to='core.brand')),
                ('outlet', models.ForeignKey(blank=True, help_text='Null = whole brand; set = specific outlet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specials', to='core.outlet')),
                ('replaces', models.ForeignKey(blank=True, help_text='Brand-level special item that this outlet special replaces', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlet_replacements', to='menu.specialitem')),
            ],
            options={
                'verbose_name': 'Special Item',
                'verbose_name_plural': 'Special Items',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveSmallIntegerField(default=1)),
                ('image', models.ImageField(upload_to='menu/booklet/')),
                ('width', models.PositiveIntegerField(default=800)),
                ('height', models.PositiveIntegerField(default=1200)),
                ('menu_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='menu.menusource')),
            ],
            options={
                'verbose_name': 'Menu Page',
                'verbose_name_plural': 'Menu Pages',
                'ordering': ['page_number', 'id'],
                'unique_together': {('menu_source', 'page_number')},
            },
        ),
    ]
