# Generated by Django 6.0.8 on 2026-10-06 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_brand_default_menu_url_brand_default_ordering_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(default='Dish Match & Win!', max_length=120)),
                ('game_type', models.CharField(choices=[('memory', 'Memory Match'), ('puzzle', 'Slide Puzzle'), ('tap', 'Tap Timing')], default='memory', max_length=16)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='{"pairs": 6, "time_limit_sec": 90, "icons": ["biryani", "grill", "tea", "cake", "salad", "burger"]}')),
                ('enabled', models.BooleanField(default=True)),
                ('win_probability', models.FloatField(default=0.85, help_text='Probability (0.0 - 1.0) of issuing a reward when game is successfully completed')),
                ('reward_type', models.CharField(choices=[('percent', 'Percentage Discount'), ('amount', 'Fixed AED Amount')], default='percent', max_length=12)),
                ('discount_percent', models.PositiveSmallIntegerField(default=10, help_text='e.g. 5, 10, or 15%')),
                ('coupon_amount', models.DecimalField(decimal_places=2, default=10.0, help_text='e.g. 10.00 AED', max_digits=6)),
                ('coupon_prefix', models.CharField(default='KC', max_length=10)),
                ('max_winners', models.PositiveIntegerField(default=500, help_text='Total cap of rewards issued')),
                ('daily_limit', models.PositiveIntegerField(default=25, help_text='Maximum winners per calendar day')),
                ('per_device_daily_limit', models.PositiveSmallIntegerField(default=1, help_text='Maximum rewards per device hash per calendar day')),
                ('voucher_valid_days', models.PositiveSmallIntegerField(default=7, help_text='Number of days reward is valid after issuance')),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core.brand')),
                ('outlet', models.ForeignKey(blank=True, help_text='Null = brand-wide default game; set = outlet-specific override', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core.outlet')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reward_type', models.CharField(choices=[('percent', 'Percentage Discount'), ('amount', 'Fixed AED Amount')], max_length=12)),
                ('reward_value', models.CharField(help_text="e.g. '10% OFF' or '10 AED OFF'", max_length=30)),
                ('coupon_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('device_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('void', 'Void')], db_index=True, default='issued', max_length=12)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='games.game')),
                ('outlet', models.ForeignKey(help_text='Outlet where the QR was scanned (mandatory)', on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='core.outlet')),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='core.qrcode')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_redeemed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['outlet', 'status'], name='games_rewar_outlet__efb463_idx'), models.Index(fields=['game', 'issued_at'], name='games_rewar_game_id_0032c3_idx')],
            },
        ),
    ]
