# Generated by Django 6.1.1 on 2026-10-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended')], default='draft', max_length=10),
        ),
    ]
