# Generated by Django 6.0.8 on 2026-10-06 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_campaign_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='default_menu_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='default_ordering_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='outlet',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='menu_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='ordering_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='slug',
            field=models.SlugField(blank=True, help_text='e.g. international-city', max_length=60),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: [
                apps.get_model('core', 'Outlet').objects.filter(id=o.id).update(slug=o.code.lower().replace('_', '-'))
                for o in apps.get_model('core', 'Outlet').objects.all()
            ],
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='outlet',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='label',
            field=models.CharField(blank=True, help_text='e.g. KC-IC-001', max_length=60),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='scan_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='pagemodule',
            name='module_type',
            field=models.CharField(choices=[('identity', 'Brand / outlet identity'), ('hours', 'Open/closed status & timings'), ('campaign', 'Current campaign'), ('offers', 'Special offers'), ('menu', 'Full menu'), ('google_review', 'Google review'), ('instagram', 'Instagram'), ('social', 'Other social links'), ('order', 'Order / Enquire'), ('whatsapp', 'WhatsApp'), ('call', 'Call'), ('directions', 'Directions'), ('feedback', 'Feedback'), ('footer', 'Footer'), ('game', 'Play a game & win a discount')], max_length=24),
        ),
        migrations.AlterUniqueTogether(
            name='outlet',
            unique_together={('brand', 'slug')},
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('object_repr', models.CharField(max_length=200)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.outlet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Change Log',
                'verbose_name_plural': 'Change Logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='OutletManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_edit_contact', models.BooleanField(default=False)),
                ('outlets', models.ManyToManyField(blank=True, related_name='managers', to='core.outlet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outlet Manager',
                'verbose_name_plural': 'Outlet Managers',
            },
        ),
    ]
