# Generated by Django 6.1.1 on 2026-10-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_brand_default_menu_url_brand_default_ordering_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletmanager',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Set for brand managers: scope is all outlets of this brand', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='core.brand'),
        ),
        migrations.AddField(
            model_name='outletmanager',
            name='role',
            field=models.CharField(choices=[('outlet_manager', 'Outlet Manager'), ('brand_manager', 'Brand Manager')], default='outlet_manager', max_length=20),
        ),
    ]
