# Generated by Django 6.1.1 on 2026-10-06 18:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_brand_default_menu_url_brand_default_ordering_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(help_text='E.164, e.g. +971501234567', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Family',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('min_duration_ms', models.PositiveIntegerField(default=5000)),
                ('max_duration_ms', models.PositiveIntegerField(default=600000)),
                ('max_score', models.PositiveIntegerField(default=150)),
                ('max_score_per_second', models.FloatField(default=2.5)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Play game',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='KidProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('avatar', models.CharField(max_length=30)),
                ('points_balance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='kidsplay.family')),
            ],
            options={
                'verbose_name': 'Kid profile',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('game', 'Game'), ('bill_bonus', 'Bill bonus'), ('redemption', 'Redemption'), ('admin_adjust', 'Admin adjust'), ('reversal', 'Reversal')], max_length=16)),
                ('ref_type', models.CharField(blank=True, max_length=40)),
                ('ref_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kidsplay_ledger', to=settings.AUTH_USER_MODEL)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='kidsplay.kidprofile')),
            ],
            options={
                'verbose_name': 'Points ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='kidsplay/rewards/')),
                ('cost_points', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Blank means unlimited', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kidsplay_rewards', to='core.outlet')),
            ],
            options={
                'ordering': ['cost_points', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TableVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('bill_ref', models.CharField(blank=True, max_length=40)),
                ('bill_bonus_awarded', models.BooleanField(default=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='kidsplay.family')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kidsplay_visits', to='core.outlet')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kidsplay_visits', to='core.qrcode')),
            ],
            options={
                'verbose_name': 'Table visit',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_nonce', models.CharField(max_length=32, unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('reported_score', models.IntegerField(blank=True, null=True)),
                ('reported_duration_ms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('finished', 'Finished'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='started', max_length=12)),
                ('reject_reason', models.CharField(blank=True, max_length=40)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='kidsplay.kidprofile')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='kidsplay.playgame')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='kidsplay.tablevisit')),
            ],
            options={
                'verbose_name': 'Game session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='kidsplay.playgame')),
            ],
            options={
                'ordering': ['min_score'],
                'constraints': [models.UniqueConstraint(fields=('game', 'min_score'), name='kidsplay_tier_unique')],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kidsplay_redemptions', to=settings.AUTH_USER_MODEL)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='kidsplay.kidprofile')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='kidsplay.reward')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('code',), name='kidsplay_pending_code_unique')],
            },
        ),
    ]
