# Generated by Django 6.1.1 on 2026-10-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('user_agent', models.CharField(blank=True, max_length=240)),
                ('ip_hash', models.CharField(blank=True, help_text='Salted hash only — raw IPs are never stored', max_length=64)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='core.brand')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_events', to='core.campaign')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='core.outlet')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='core.qrcode')),
            ],
            options={
                'verbose_name': 'Scan Event',
                'verbose_name_plural': 'Scan Events',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
