# Generated by Django 6.0.8 on 2026-10-06 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0003_brand_default_menu_url_brand_default_ordering_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('specials', 'Specials'), ('menu', 'Menu'), ('review', 'Google Review'), ('instagram', 'Instagram'), ('game', 'Play Game'), ('directions', 'Directions'), ('call', 'Call'), ('order', 'Order Online')], max_length=32)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Tap Event',
                'verbose_name_plural': 'Tap Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='scanevent',
            name='device_class',
            field=models.CharField(blank=True, default='mobile', max_length=20),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='referrer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='session_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['outlet', 'scanned_at'], name='analytics_s_outlet__090479_idx'),
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['qr_code', 'scanned_at'], name='analytics_s_qr_code_02dcd8_idx'),
        ),
        migrations.AddField(
            model_name='tapevent',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tap_events', to='core.brand'),
        ),
        migrations.AddField(
            model_name='tapevent',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tap_events', to='core.outlet'),
        ),
        migrations.AddField(
            model_name='tapevent',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tap_events', to='core.qrcode'),
        ),
        migrations.AddIndex(
            model_name='tapevent',
            index=models.Index(fields=['outlet', 'action', 'created_at'], name='analytics_t_outlet__7faec7_idx'),
        ),
        migrations.AddIndex(
            model_name='tapevent',
            index=models.Index(fields=['brand', 'action', 'created_at'], name='analytics_t_brand_i_da2200_idx'),
        ),
    ]
